version: 0.0
os: linux
files:
  - source: blog
    destination: /tmp/deploy/blog
  - source: corporate
    destination: /tmp/deploy/corporate
permissions:
    - object: /opt/applications/
      owner: www-data
      group: www-data
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
